config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'

  get '/login' => 'session#new'
  post '/login' => 'session#login'
  get '/logout' => 'session#logout'

  get '/register' => 'session#register'

  post '/register' => 'users#create'

  get '/comments/:id/upvote' => 'comments#upvote'

  get '/comments/:id/downvote' => 'comments#downvote'

  get '/users/:username/games/:game_name/add' => 'games#owned'

  get '/games/:game_name/rate/:rate_value' => 'games#rate_game'

  resources :users, only: [:new, :create]

  resources :games, only: [:new, :create]

  # resources :games, only: [:show, :edit, :update, :destroy], param: :game_name

  resources :games, only: [:show, :edit, :update, :destroy], param: :game_name do
    resources :ratings, only: [:new, :create]
  end

  resources :users, only: [:show, :edit, :update, :destroy], param: :username

  resources :tags, only: [:new, :create,]

  resources :tags, only: [:new, :create, :index]

  resources :tags, only: [:show], param: :tag_name

  resources :comments, only: [:new, :create, :destroy]

end

app/models/game.rb
class Game < ActiveRecord::Base

  has_many :taggings

  has_many :tags, through: :taggings

  has_many :ownerships

  has_many :owners, through: :ownerships

  has_many :comments

  has_many :ratings, foreign_key: :rater_id

  validates :name, uniqueness: true

  validates :name, presence: true

  accepts_nested_attributes_for :tags

  def average_rating
    return 0 if ratings.length == 0
    ratings = self.ratings
    total = ratings.reduce(0) do |sum, rating|
      sum + rating.value
    end
    return total / ratings.length
  end

  def ratings_sort(games)
    games.sort{|first, second| first.average_rating <=> second.average_rating}
  end

  def self.all_rated_high_to_low
    Game.all.sort{|first, second| first.average_rating <=> second.average_rating}
  end

  def url
    URI.escape(self.name)
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController

  # def create
  #   @game = Game.new(game_params)
  #   p @game
  #   if @game.save
  #     redirect_to '/'
  #   else
  #   end
  # end

  def index
  end

  def new
    @game = Game.new
    @game.tags.build
  end

  def rate_game
    @game = Game.find_by(name: params[:game_name])
    rating_value = params[:rate_value]
    current_user.ratings << Rating.new(rater_id: current_user.id, value: rating_value, game_id: @game.id)
    redirect_to "/users/#{current_user.url}"
  end

  def show
    @comment = Comment.new
    @game = Game.find_by(name: params[:game_name])
  end


  def create
    # p params
    # p game_params
    # p "========================================"
    # p tag_list
    #   p "========================================"
    @game = Game.new(game_params)
    if @game.save


      tags_string = tag_names_list
      tags_array = tags_string.split(',')
      if tags_array.count > 0
        tags_array.each do |tag|
          @game.tags << Tag.find_or_create_by(name: tag)
        end
      end


      flash.delete(:errors)
      redirect_to "/games/#{@game.url}"
    else
      flash[:errors] = @game.errors.full_messages
      redirect_to '/games/new'
    end
  end

  def show
    @game = Game.find_by(name: params[:game_name])
    @comment = Comment.new
  end

  def edit
    redirect_to "/"
    # @game = Game.find_by(name: params[:game_name])
  end

  def update
    redirect_to "/"
    # @game = Game.find_by(name: params[:game_name])
    # @game.update(game_params)
    # if @game.save
    #   tags_string = tag_names_list
    #   tags_array = tags_string.split(',')
    #   if tags_array.count > 0
    #     tags_array.each do |tag|
    #       @game.tags << Tag.find_or_create_by(name: tag)
    #     end
    #   end


    #   flash.delete(:errors)
    #   redirect_to "/games/#{@game.url}"
    # else
    #   flash[:errors] = @game.errors.full_messages
    #   redirect_to '/games/new'
    # end
  end

  def owned
    game = Game.find_by(name: params[:game_name])
    current_user.owned_games << game
    redirect_to "/games/#{game.url}"
  end



private
  def game_params
    params.require(:game).permit(:name, :description, :rules_url, :image_url)
  end

  def tag_names_list
    params.require(:game).permit(tags_attributes: [:names_list])[:tags_attributes]["0"][:names_list]
  end

end

app/views/games/edit.html.erb
<div class = "container">
  <% if game ||= nil %>
    <% @game ||= game %>
  <% end %>
  <% if flash[:errors] %>
    <%= render partial: 'partials/errors' %>
  <% end %>
  <div class="jumbotron">
    <%= form_for @game do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>       <br>
      <%= f.label :description %>

      <%= f.text_field :description %>
      <br>
      <%= f.label :rules_url %>
      <%= f.text_field :rules_url %>      <br>
      <%= f.label :image_url %>
      <%= f.text_field :image_url %>      <br>
      <%= f.fields_for :tags do |tag_form| %>
        <%= f.label :tag %>
        <%= tag_form.text_field :name %>      <br>
        <% end %>
      <%= f.submit "Update Game!" %>
    <% end %>
  </div>
</div>

app/views/games/new.html.erb
<div class = "container">
  <% if @game ||= nil %>
    <% @game ||= game %>
  <% end %>
  <% if flash[:errors] %>
    <%= render partial: 'partials/errors' %>
  <% end %>
  <div class="jumbotron">
    <%= form_for @game do |f| %>
      <%= f.text_field :name, placeholder: "Name" %>       <br>
      <%= f.text_field :description, placeholder: "Description" %>
      <br>
      <%= f.text_field :rules_url, placeholder: "Link To Rules" %>      <br>
      <%= f.text_field :image_url, placeholder: "Link To Image Of Game" %>      <br>
      <%= f.fields_for :tags do |tag_form| %>
        <%= tag_form.text_field :names_list, placeholder: "Tags, separated by commas" %>      <br>
        <% end %>
      <%= f.submit "Add Game!" %>
    <% end %>
  </div>
</div>

app/views/games/show.html.erb
<div class = 'container'>
  <div class ='jumbotron'>
    <div class = "gameShow">
      <h2><%= @game.name %></h2>
      <span>Overall Rating: <%= @game.average_rating %></span>

      <div class= "gameBox">
        <img class="img" src="<%= @game.image_url %>">
        <p>Description: <%= @game.description %></p>
        <p><a href="<%= @game.rules_url %>">Rules</a></p>
      </div>


  <% if logged_in? && owner?(@game) %>
    <%= form_tag(tags_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search tags" %>
      <%= submit_tag "Search Tags", :name => nil %>
    <% end %>
  <% end %>

</div>

<div class="gameBox">
  <h5>Tags: </h5>
  <% @game.tags.each do |tag| %>
    <ul>
      <li><%= link_to "#{tag.name}", tag_path(tag.name) %></li>
    </ul>
  <% end %>
</div>

<% if logged_in? %>
  <div style="width:70%; margin: 20px; border: 1px dotted grey; padding: 5px">
    <h3>Owners: </h3>
      <ul>
        <% @game.owners.each do |owner| %>
          <li><%= owner.username %></li>
        <% end %>
      </ul>
      <%if !current_user.owned_games.include?(@game) %>
        <%= link_to "I Own This Game", "/users/#{current_user.url}/games/#{@game.url}/add", class: "game-add-link" %>
      <% end %>
  </div>
<% end %>

<% if logged_in? %>
  <div class="comment-container">
    <% @game.comments.each do |comment| %>
      <%= render partial: 'partials/comment', locals: {comment: comment} %>
    <% end %>
  </div>

  <div class="comment-form-container">
    <% if !@comment.errors.empty? %>
      <%= render partial: 'partials/errors' %>
    <% end %>
    <%= render partial: 'partials/comment_form' %>
  </div>
<% end %>